baseurl = "https://ruushwei.github.io/"
copyright = "张宏伟"
disqusshortname = "vjeantet"
languagecode = "fr-FR"
paginate = 5
pluralizelisttitles = false
theme = "casper"
title = "Hongwei's Blog"



[[menu.main]]
identifier = "blog"
name = "主页"
url = "/"
weight = -120

[[menu.main]]
name = "java"
url = "/tags/java"
weight = 101

[[menu.main]]
name = "linux"
url = "/tags/linux"
weight = 102

[[menu.main]]
name = "sql"
url = "/tags/sql"
weight = 109

[[menu.main]]
name = "front-end"
url = "/tags/front-end"
weight = 109

[[menu.main]]
name = "framework"
url = "/tags/framework"
weight = 109

[[menu.main]]
name = "algorithm"
url = "/tags/algorithm"
weight = 109


[[menu.main]]
name = "关于我"
url = "/about"
weight = 109


[params]
author = "张宏伟"
authorlocation = "北京"
authorwebsite = "blog.hongwei.online"
bio = "沃德天辣么帅"
cover = "images/cover_polenord.jpg"
description = "Talk is cheap,show me the code."
githubName = "ruushwei"
googleAnalyticsUserID = "UA-79101-12"
hideHUGOSupport = false
logo = "images/logo1.png"
twitterName = ""
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
