baseurl = "https://ruushwei.github.io/"
copyright = "张宏伟"
disqusshortname = "vjeantet"
languagecode = "fr-FR"
paginate = 20
pluralizelisttitles = false
theme = "casper"
title = "宏伟的博客"



[[menu.main]]
identifier = "blog"
name = "主页"
url = "/"
weight = -120

[[menu.main]]
name = "java"
url = "/tags/java"
weight = 101

[[menu.main]]
name = "linux"
url = "/tags/linux"
weight = 102

[[menu.main]]
name = "sql"
url = "/tags/sql"
weight = 103

[[menu.main]]
name = "前端"
url = "/tags/qianduan"
weight = 104

[[menu.main]]
name = "框架"
url = "/tags/framework"
weight = 105


[[menu.main]]
name = "算法"
url = "/tags/suanfa"
weight = 106

[[menu.main]]
name = "数据结构"
url = "/tags/data_structure"
weight = 107
[[menu.main]]
name = "设计模式"
url = "/tags/design_mode"
weight = 108

[[menu.main]]
name = "springmvc"
url = "/tags/springmvc"
weight = 109




[[menu.main]]
name = "mybatis"
url = "/tags/mybatis"
weight = 110

[[menu.main]]
name = "hibernate"
url = "/tags/hibernate"
weight = 112

[[menu.main]]
name = "struts"
url = "/tags/struts"
weight = 113

[[menu.main]]
name = "spring"
url = "/tags/spring"
weight = 114

[[menu.main]]
name = "server"
url = "/tags/spring"
weight = 115


[[menu.main]]
name = "随笔"
url = "/tags/suibi"
weight = 119

[[menu.main]]
name = "我"
url = "/about"
weight = 121


[params]
author = "张宏伟"
authorlocation = "北京"
authorwebsite = "blog.hongwei.online"
bio = "沃德天辣么帅"
cover = "images/bg.jpg"
description = "让编程成为乐趣，让学习变得纯粹。"
githubName = "ruushwei"
googleAnalyticsUserID = "UA-79101-12"
hideHUGOSupport = false
logo = "images/logo1.png"
twitterName = ""
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
